name: parky
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.7.0
  gradient_borders: ^1.0.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/

